version: '3.3'
# Dear Bug Hunter
# This credential is intentionally included for educational purposes only and does not provide access to any production systems
# Please do not submit it as part of our bug bounty program
services:
  db2:
    image: icr.io/db2_community/db2:12.1.0.0
    privileged: true
    ports:
     - "50000:50000"
    environment:
      LICENSE: "accept"
      DB2INSTANCE: "db2inst1"
      DB2INST1_PASSWORD: "password"
      DBNAME: "testdb"
      BLU: "false"
      ENABLE_ORACLE_COMPATIBILITY: "false"
      UPDATEAVAIL: "NO"
      TO_CREATE_SAMPLEDB: "true"
      REPODB: "true"
      IS_OSXFS: "false"
      PERSISTENT_HOME: "false"
      HADR_ENABLED: "false"
      ETCD_ENDPOINT: 
      ETCD_USERNAME:
      ETCD_PASSWORD:
